DISCORD_TOKEN = "OTMxMTI4NzEwNTI0OTg1MzY0.Yd_7MA.56YDkY-HfwMT3MBtW_jhY__SeZM"
TENOR_API_KEY = "UTJAVRYK3DSA"
REDDIT_CLIENT_ID = "X53dzVo6z_diIuhzZj8MJQ"
REDDIT_API_SECRET_KEY = "nSPbaOKkfE0K6IIn89iLxpikX9uYSw"
REDDIT_USERNAME = "kinglacto"
REDDIT_PASSWORD = "Test4@apps.nhg123"

